### ISSUE TITLE
Requesting Data?

### ISSUE THREAD

**Issue by sjc625** [UML-SpaceHAUC/lumberjack#3]
Is there a way to fill all of the data (aData.etc....)? Currently the logger would need to be subscribed to each of those topics, and then log the data when it changes/when the logger thinks it should (on a timer??) The current implementation assumes the data is globally available, which it is not.

**Comment by DarrienG** [comment]
You're misunderstanding how OctopOS works, it is not a pull model, it is a push model. Lumberjack subscribes to the logging topic, and then whenever any of the relevant types wants to log, it will send a logging event.  

Lumberjack is subscribed to a logging event. The logging event will contain a struct with the data they want to record and the type of data they are sending. See saving in the README https://github.com/SPACE-HAUC/lumberjack/blob/master/README.md#saving

It works the same way with dumping. Send it a dump event with the the type you want and it will dump it.

Lumberjack only expects to receive one type of struct per event, so each subsystem can log independently without doing any weird bundling.

**Comment by DarrienG** [comment]
Feel free to contact me if you need help understanding.
